"""add notary_stats table

Revision ID: 13a944d3ea46
Revises: b42576baa109
Create Date: 2026-03-19 15:28:42.032328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a944d3ea46'
down_revision: Union[str, Sequence[str], None] = 'b42576baa109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notary_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('postal_code', sa.String(length=5), nullable=False),
    sa.Column('notary_price_sqm', sa.Integer(), nullable=True),
    sa.Column('notary_avg_price', sa.Integer(), nullable=True),
    sa.Column('notary_avg_surface', sa.Integer(), nullable=True),
    sa.Column('notary_transactions', sa.Integer(), nullable=True),
    sa.Column('notary_total', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notary_stats_postal_code'), 'notary_stats', ['postal_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notary_stats_postal_code'), table_name='notary_stats')
    op.drop_table('notary_stats')
    # ### end Alembic commands ###
