"""add_financial_analyses_table

Revision ID: 29ddff7d5d80
Revises: b6d9bcc0b86b
Create Date: 2026-03-11 10:56:01.222510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ddff7d5d80'
down_revision: Union[str, Sequence[str], None] = 'b6d9bcc0b86b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('size_sqm', sa.Float(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('capex_total', sa.Float(), nullable=True),
    sa.Column('capex_months', sa.Integer(), nullable=True),
    sa.Column('project_months', sa.Integer(), nullable=True),
    sa.Column('exit_price_per_sqm', sa.Float(), nullable=True),
    sa.Column('monthly_opex', sa.Float(), nullable=True),
    sa.Column('ibi_annual', sa.Float(), nullable=True),
    sa.Column('closing_costs_pct', sa.Float(), nullable=True),
    sa.Column('broker_fee_pct', sa.Float(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('mortgage_ltv', sa.Float(), nullable=True),
    sa.Column('mortgage_rate_annual', sa.Float(), nullable=True),
    sa.Column('capex_debt', sa.Float(), nullable=True),
    sa.Column('capex_debt_rate_annual', sa.Float(), nullable=True),
    sa.Column('irr', sa.Float(), nullable=True),
    sa.Column('moic', sa.Float(), nullable=True),
    sa.Column('return_on_equity', sa.Float(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('gross_exit_price', sa.Float(), nullable=True),
    sa.Column('net_exit_price', sa.Float(), nullable=True),
    sa.Column('total_dev_cost', sa.Float(), nullable=True),
    sa.Column('max_equity_exposure', sa.Float(), nullable=True),
    sa.Column('closing_costs', sa.Float(), nullable=True),
    sa.Column('broker_fee', sa.Float(), nullable=True),
    sa.Column('mortgage_debt', sa.Float(), nullable=True),
    sa.Column('total_debt', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_analyses')
    # ### end Alembic commands ###
