"""add construction_type and property_class to notary_stats

Revision ID: 5aa532c4a164
Revises: 13a944d3ea46
Create Date: 2026-03-19 16:07:40.021846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa532c4a164'
down_revision: Union[str, Sequence[str], None] = '13a944d3ea46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Clear existing data before adding NOT NULL columns
    op.execute("DELETE FROM notary_stats")
    op.add_column('notary_stats', sa.Column('construction_type', sa.String(length=20), nullable=False, server_default='todos'))
    op.add_column('notary_stats', sa.Column('property_class', sa.String(length=20), nullable=False, server_default='todos'))
    op.drop_index(op.f('ix_notary_stats_postal_code'), table_name='notary_stats')
    op.create_index(op.f('ix_notary_stats_postal_code'), 'notary_stats', ['postal_code'], unique=False)
    op.create_unique_constraint('uq_notary_postal_tipo_clase', 'notary_stats', ['postal_code', 'construction_type', 'property_class'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notary_stats_postal_code'), table_name='notary_stats')
    op.create_index(op.f('ix_notary_stats_postal_code'), 'notary_stats', ['postal_code'], unique=True)
    op.drop_column('notary_stats', 'property_class')
    op.drop_column('notary_stats', 'construction_type')
    # ### end Alembic commands ###
