"""extend deal fields

Revision ID: b6d9bcc0b86b
Revises: 35cecb4c82a0
Create Date: 2026-03-10 18:53:57.092993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d9bcc0b86b'
down_revision: Union[str, Sequence[str], None] = '35cecb4c82a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('district', sa.Text(), nullable=True))
    op.add_column('deals', sa.Column('zone', sa.Text(), nullable=True))
    op.add_column('deals', sa.Column('condition', sa.Text(), nullable=True))
    op.add_column('deals', sa.Column('orientation', sa.Text(), nullable=True))
    op.add_column('deals', sa.Column('storage_room', sa.Boolean(), nullable=True))
    op.add_column('deals', sa.Column('terrace', sa.Boolean(), nullable=True))
    op.add_column('deals', sa.Column('balcony', sa.Boolean(), nullable=True))
    op.add_column('deals', sa.Column('elevator', sa.Boolean(), nullable=True))
    op.add_column('deals', sa.Column('garage', sa.Boolean(), nullable=True))
    op.add_column('deals', sa.Column('listed_date', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'deals', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deals', type_='unique')
    op.drop_column('deals', 'listed_date')
    op.drop_column('deals', 'garage')
    op.drop_column('deals', 'elevator')
    op.drop_column('deals', 'balcony')
    op.drop_column('deals', 'terrace')
    op.drop_column('deals', 'storage_room')
    op.drop_column('deals', 'orientation')
    op.drop_column('deals', 'condition')
    op.drop_column('deals', 'zone')
    op.drop_column('deals', 'district')
    # ### end Alembic commands ###
